### ISSUE TITLE
Support for tags

### ISSUE THREAD

**Issue by andinus** [tanujnotes/Olauncher#11]
There's this application called Materialistic which is a Hacker News client. Currently typing "materi" opens it, with tagging, just "hn" would open it.

**Comment by andinus** [comment]
KISS Launcher supports this, it's also a search based launcher.

**Comment by tanujnotes** [comment]
Olauncher currently doesn't have a database and this would require a database implementation. Too much work for too little gain. Closing this for now as there are a lot of high priority issues to work on. It may be reconsidered in the future if enough people require it. Thank you.

**Comment by andinus** [comment]
Makes sense. This will also fix #12. Users could just add tags instead of changing names in app list.

Also, maybe we could hardcode tags for applications? Like Materialistic would map to HN, RedReader to reddit, etc.? It'll be incomplete but will improve searches.

**Comment by erazemkokot** [comment]
> This will also fix #12.
The issue I posted wouldn't really be fixed with tags, because that's not the intention of it, the intention is to be able to change the apps' names, so that they are more easily recognisable or don't have unecessary text like "Fennec F-Droid" (F-Droid is not really needed there when looking at the desktop).

I am voting for tags to be implemented sometime in the future though.
