### ISSUE TITLE
Triple tap to change themes doesn't work with daily wallpaper set to `Off`

### ISSUE THREAD

**Issue by JacksonCampbell99** [tanujnotes/Olauncher#125]
I often like to change my theme with the daily wallpaper off, so I quickly assumed that that was the reason it wasn't working for me. After testing the theory I found that I was correct. I would appreciate if it worked with the daily wallpaper off, but knowing you, I wouldn't be surprised if there's a specific reason why you didn't allow it to.

**Comment by tanujnotes** [comment]
With daily wallpaper off, if someone has a particular wallpaper and they accidentally changed the theme, text might look weird, they won't understand what happened and probably give a bad rating thinking it's a bug.

Although this can be easily avoided by showing them a message when they triple tap very first time. So that's what I'll do in the next update. Stay tuned.

**Comment by JacksonCampbell99** [comment]
Thanks! And I'd love if it would switch between black and white background if I had held the on/off switch to set it to default (black). Although I do like seeing it black and turning it on light theme so it is all black as you see here:
![Screenshot_20210926-140232_Olauncher.jpg](https://user-images.githubusercontent.com/76508020/134820801-ffd9aa21-ddcb-409a-b675-55b8bc14954e.jpg)
