### ISSUE TITLE
Show status bar

### ISSUE THREAD

**Issue by andinus** [tanujnotes/Olauncher#13]
Maybe add an option to show status bar. Currently, after unlocking (biometric), I have to open the notification panel to check for notifications. They don't show up when the screen is locked for obvious reasons so it's just an annoyance. 

If status bar is shown then users can just check for notifications there.

**Comment by tanujnotes** [comment]
Showing status bar pollutes the current ultra minimal look that most users seem to love so there's no plan to do it for now. Sorry for the inconvenience.  If it's any help, you can swipe down anywhere on the home screen and it will open the notification panel. Thank you for using Olauncher.

**Comment by FilipRoseen-refp** [comment]
I was just about to create a ticket regarding this. Just started using OLauncher and would love to be able to see the status bar on the home screen. Given that this issue is flagged as `wontfix`, and that quite recently, would you simply recommend;

-  to fork the repo and add an option to show the status bar there, or;
- would you consider accepting pull-requests that would add such functionality, or;
- is there any possibility of this feature being added by maintainers of this repo?

It would be a very nice feature to be able to show it. I do agree with you, some might like the minimalism that comes from hiding it but I am sure that there are a lot of users (like myself) who would be able to see the status while being on the home screen.

**Comment by tanujnotes** [comment]
Hi, I'll see what I can do about the status bar. Maybe it can be added while removing the clock widget to maintain the clean look. Your patience is appreciated.

**Comment by FilipRoseen-refp** [comment]
I will clone the repo and probably submit a PR for this issue if you accept such. Given that there are no PRs so far, does that imply that you do not work with such?

**Comment by tanujnotes** [comment]
No that's not the case at all. Feel free to make the pull request. Thanks in advance.
