### ISSUE TITLE
Multitasking/split screen not possible with Olauncher

### ISSUE THREAD

**Issue by ANDREW007CZ** [tanujnotes/Olauncher#168]
On Xperia 5 III with A11 spliting the screen to accomodate two apps simultaneously is not possible. Possibly some kind of a bug.
When I try to click the icon to split the screen it says that it is not possible while using Olauncher.
Since it is great function to have on a device with such long display I plead to have it working.

Thank you

**Comment by ANDREW007CZ** [comment]
update - not possible even with Android 12 on this device

**Comment by tanujnotes** [comment]
Can you please download any other launcher and try multitasking? Need to figure out if it's Android  issue or Olauncher issue.

**Comment by latenights** [comment]
I can confirm that it does not work.  The screen can be split when I use other launcher (Moto App Launcher) on Android 12.

**Comment by ANDREW007CZ** [comment]
Sorry for delayed answer. Yes, with others, it works, like stock launcher, KISS launcher etc..

**Comment by YuriiZhydetskyi** [comment]
Works good on Pixel 7 (Android 13) and OnePlus 7T (Android 11)

**Comment by ChayoteJarocho** [comment]
@tanujnotes I can repro this problem in my Pixel 7 Pro.

I thought it was a problem with Android 12. I just updated to Android 13, and the problem is still there. I switched back to the default Pixel launcher and Split Top works fine. I came back to OLauncher and I can repro the issue consistently.

**Comment by ChayoteJarocho** [comment]
UPDATE: I discovered that Microsoft Launcher also had the same problem, which means the issue is NOT related to OLauncher. I digged on the internet a bit, and found that this issue happens in recent versions of android if you disable animations. The fix consists in re-enabling them in the accessibility settings. Here's a thread with more info:

https://support.google.com/pixelphone/thread/156924254/split-screen-stopped-working-after-one-od-the-latest-updates?hl=en

I was able to fix this. Hope this works for everyone else.
