### ISSUE TITLE
Main view displaying after search

### ISSUE THREAD

**Issue by guillaumeboehm** [tanujnotes/Olauncher#197]
This is a bit of a weird and specific bug, I am not sure this will be consistent across devices.

When I open certain applications with a search, instead of the application launching directly, the main view of the launcher is shown and then the application is launched.

This is happening for me with google calendar and twitch for example, calendar is the longest to launch.

What I expect:
- Swipe up
- type "calendar"
- Google calendar opens

What actually happens:
- Swipe up
- type "calendar"
- search view switches to main view
- Then google calendar opens

**Comment by tanujnotes** [comment]
This happens because the launcher aggressively switches to home screen whenever there's a hint of user switching to anything else. (I can't remember now but I had good reasons to make it like this) So whenever the app takes some time to launch, user can see the home screen for a moment.

I have added a fix for this. It looks fine for now but if I see any unintended side effects, I'll switch it back.

**Comment by tanujnotes** [comment]
Some users complained that app drawer is not closing automatically when they switch to other apps. Switching back to older implementation until I figure out a better solution for this.

**Comment by jooooscha** [comment]
One solution would be to move the call to `backToHomeScreen()` to `override onResume` instead of the uesr-leave and onStop functions.

In This case there could be a short moment where you sitll see the app drawer (the app list) after going back to olauncher. I am thinkin about implementing it that way in my forked version

**Comment by tanujnotes** [comment]
I did it. Moved it to onStop but it just doesn't work on some older versions of Android. onStop doesn't get called even if you move to a different app.

**Comment by tanujnotes** [comment]
That showing of app drawer for a split second is highly undesirable.
Besides, on newer devices, apps launch quick enough that you don't get to see the home screen before app launch so this is not a big problem. But of course it can be improved.
