### ISSUE TITLE
Feature Request: ability to remove home items

### ISSUE THREAD

**Issue by HugoDF** [tanujnotes/Olauncher#2]
Thanks for this launcher, would it be possible to add the ability to remove/unselect apps for the home screen.

I'm happy to try to contribute if if you don't have time but can give me some pointers as to how I would go about it

**Comment by tanujnotes** [comment]
This will feature will be available in the next update where you'd be able to choose to have anywhere from 0 to 4 (or 5 maybe) apps on the home screen.

**Comment by ViliusSutkus89** [comment]
Hey @tanujnotes, nice app, thanks.

>anywhere from 0 to 4 (or 5 maybe) apps on the home screen

Is there a particular reason why there can't be a longer list of favorite apps on the home screen?

**Comment by tanujnotes** [comment]
No particular reason. I tried other different combinations and 4 looked best.

By the way you, can swipe left and right to open Phone and Camera apps. You can also click on time and date to open Alarm and Calendar apps respectively. So in total you have 8 apps on home screen, 4 of which you can customize.

**Comment by ViliusSutkus89** [comment]
>4 looked best

I find it hard to understand the reasoning. With max amount not being limited, users could just voluntarily not add items past the 4 count, if it makes the list look worse.

**Comment by tanujnotes** [comment]
There's no strong logical reason behind this decision if you're looking for one. Two points that somewhat contributed to this decision are - 1. It's a minimalistic app so I'm always thinking about what else can I remove instead of adding. 2. The ulterior motives of this launcher is to make you use your phone less. That's why fewer apps on home (and left alignment of text instead of right, making it difficult to click). 


All of this can change if enough people require it. For now, most users are happy with the default options so it's staying that way for now.
