### ISSUE TITLE
App turning screen on Hytera

### ISSUE THREAD

**Issue by Droidphilev** [tanujnotes/Olauncher#21]
Hi,

I use an Android device but as network radio. This device (Hytera PNC380) has a 240x320 wich is used in landscape. Sadly enough Olauncher turns the screen to portrait. I know this is an awkward question for an awkward device but it would be nice to have your app working (not for the menu but only to put some apps on the honescreen.

**Comment by tanujnotes** [comment]
Hi, I understand your problem but allowing the launcher to turn into landscape mode will create a lot of issue with other phones. That's why it's locked into portrait mode.What I can do for you is send you a special apk with these restrictions removed. If that works for you, let me know.Best, TanujOn 22-Sep-2020 1:17 AM, Droidphilev <notifications@github.com> wrote:
Hi,
I use an Android device but as network radio. This device (Hytera PNC380) has a 240x320 wich is used in landscape. Sadly enough Olauncher turns the screen to portrait. I know this is an awkward question for an awkward device but it would be nice to have your app working (not for the menu but only to put some apps on the honescreen.

**Comment by Droidphilev** [comment]
Hello, that would be very very kind of you! We can only try :)

**Comment by tanujnotes** [comment]
Your app is ready. Please drop me an email or DM on Twitter and I'll send you the APK.

**Comment by Droidphilev** [comment]
Hi again!
I tried mailing you @frndly.app as it was the only address i could find. Sadly enough the message could not be delivered.

**Comment by tanujnotes** [comment]
Solved.
