### ISSUE TITLE
Add a font border

### ISSUE THREAD

**Issue by exadeci** [tanujnotes/Olauncher#22]
Hello,

Thanks for the great launcher it replaced KISS for me that I had been using for more than a year.
One thing that bothers me a bit though is that the font can be hard to read when it's white on white or black on black.

The simple fix is to switch the font between the two **but** some wallpapers have both white and black so the font is really hard to read regardless of the color.

So I think being able to add a border to font should help with this.

**Comment by dar5hak** [comment]
Another option is to dim the wallpaper just enough that white text offers the necessary contrast. Would look more elegant IMO.

**Comment by tanujnotes** [comment]
I have added a small shadow to the texts and I do dim the wallpaper a little bit for better visibility but a little more tweaking is required. Here's what I'm thinking for the next update. We don't need to worry too much about the visibility on home screen because users already know what apps are where as they are the ones who selected it and the location is fixed, more or less. But when opening app drawer or settings, dim the wallpaper significantly to increase the contrast and thus text visibility.

Please wait until the next update and then we'll discuss if this is enough or more needs to be done. Thank you.

**Comment by tanujnotes** [comment]
Please update the app. Thank you.
