### ISSUE TITLE
Home screen click app  name

### ISSUE THREAD

**Issue by diogodh** [tanujnotes/Olauncher#23]
In the "all apps" list, although they are left aligned, if you click on the right part of the screen, it will still open the app because each app in the list is in reality a row.
The same behaviour should be present in the home screen, so i could have the apps name left aligned but open them with a click on the right side of the screen (much better due to huge screens nowadays making it hard to click on the left side with right hand).

**Comment by tanujnotes** [comment]
I want the same thing but this feature would result in a lot of accidental clicks by users. And that's why we can't have it.

Good news is that ability to rename apps is coming in the next update. So you can align home apps to the right and edit their titles in a way that they don't look too bad. That's the best I can offer for now. I hope you understand.
