### ISSUE TITLE
Option to outline text?

### ISSUE THREAD

**Issue by johnathon-walnut** [tanujnotes/Olauncher#230]
I think an option to add an outline to the text would be useful for those using a fairly light wallpaper.

**Comment by tanujnotes** [comment]
Can you post a screenshot with the wallpaper you're talking about?

**Comment by johnathon-walnut** [comment]
> I think I know what he means. It's a small detail but I also noticed it a while ago: https://repository-images.githubusercontent.com/278638069/db0acb80-661b-11eb-803e-926cae5dccb4
> 
> Now imagine the wallpaper would be brighter than those. The text ("Notes, Gallery, Spotify" etc. and the time/date) is very hard to read (white text on almost white background). This could be solved by a font with a black border (like [this](https://i.pinimg.com/736x/13/66/2a/13662acd0c2cace7ead6b699fc11721f.jpg)).

This is exactly what I mean, thank you

**Comment by tanujnotes** [comment]
Text already has a shadow. It's not very dark but it's there and it works well for the most part. I need to see some example of the issue you're talking about before making any changes. 

Another point is - home screen apps are more or less fixed for most users. Even if the visibility is not ideal, you know the position of your home screen apps once you've used Olauncher for a few days. For app drawer, I've add a background tint which increases the contrast and hence the visibility. 

If you're using a white wallpaper, you can switch to light theme which will make the text black. That's why it's there.

I have had these discussions early on and experimented enough to come to the current settings. It has been like that for at least a year with no complaints that I can remember.

If you have an issue, at the very least you'll have to produce a screenshot. The image link referred to is very old and not relevant.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/tanujnotes/Olauncher/issues/230#issuecomment-1250115853

@tanujnotes, an outline is easier to parse than a shadow is certain multilingual contexts where the characters are more detailed than Latin characters generally are.

**Comment by tanujnotes** [comment]
@RokeJulianLockhart That's a good point. I still need to see a screenshot to figure out what changes to make.
