### ISSUE TITLE
Allow specifying time for daily wallpaper update

### ISSUE THREAD

**Issue by JosephSaw** [tanujnotes/Olauncher#24]
I would like to wake up every morning to a different wallpaper but at the moment i cant specify a time for the daily wallpaper to update.

**Comment by tanujnotes** [comment]
Wallpaper updates roughly once every 24 hours and your phone decides when to do it, based on certain criteria like Internet availability, battery status etc. This is much more efficient and reliable rather than running a background service and updating the wallpaper at a fixed time every day.

What you can do for now is go to the settings at a specific time and turn the wallpaper update off and on. Let's say you did this at 1:00 AM, next day the wallpaper will update roughly at the same time. That's not guaranteed though for the reasons I mentioned above. This is the best I can offer for now. I hope you understand. Thank you.
