### ISSUE TITLE
Reminder for swipe left/right apps

### ISSUE THREAD

**Issue by cassidyjames** [tanujnotes/Olauncher#26]
A nice touch could be briefly showing the names of the swipe left/swipe right apps at the bottom of the screen, near their respective side—so by default, camera at the bottom-right and phone at the bottom-left. They could fade out after a moment to keep the uncluttered look.

This would remind new folks of the default swipe actions, and would be a nice reminder for existing folks, especially if they've set custom actions and might forget what they set.

This is similar to the Google Assistant corner gesture on my Pixel 3, where it reminds you how to do something but then gets out of the way.

I can provide a mockup if my description is unclear.

**Comment by tanujnotes** [comment]
I made an assumption earlier that users will discover every little thing that Olauncher offers eventually, given how tiny the app really is. I couldn't be more wrong. I'm going to add these tool tips for every little thing the launcher offers. It might take some time to design the whole thing. Thank you for the suggestion.

**Comment by shalzz** [comment]
Instead of introducing fading text at the bottom, I feel it would be a lot better if the respective app slides into view as one tried to swipe in either horizontal direction. It'll feel a lot more fluid as opposed to the app just poping out with the current implementation giving it a janky feel.

As for discoverability I think people generally tend to swipe naturally and combined with the immediate feedback from the above approach, people certainly won't forget that they can swipe left/right.

**Comment by tanujnotes** [comment]
Once users open settings, they can easily see that there are left and right swipe apps. Enhancements can be made I'm not worried too much about it at the moment.

That janky app opening bothers me too and I'll see what Incan do about it.

**Comment by tanujnotes** [comment]
It doesn't seem like this will be added anytime soon, if ever, so closing this.
