### ISSUE TITLE
How to distinguish apps with same name?

### ISSUE THREAD

**Issue by aggsol** [tanujnotes/Olauncher#27]
Two apps show up when I enter "maps" and both are displayed as "Maps" but which app is which? One is Google Maps the other is maps from F-Droid store.

**Comment by tanujnotes** [comment]
I'm sorry but I don't have any idea about how to fix this while maintaining the minimal design. Suggestions are more than welcome.

**Comment by aggsol** [comment]
Just an idea: Also search in the app and package name. So when I enter "Google" all apps from google appear not only the apps with "Google" in the name. If the search would allow fuzzy searching  then typing "goo ma" could bring up Google Maps as only hit.

**Comment by tanujnotes** [comment]
Searching package names is a really good idea. Don't know why I didn't think of that before. And I'll see what I can do about fuzzy search. By the way, searching 'map' or even  'lemap' will show an app titled Google Maps. I hope that's helpful. Thanks.

**Comment by tanujnotes** [comment]
I thought a little more about searching package names and I'm a little hesitant now.

Let's say an app name starts with 'droid'. User searches 'dro' and expects the launcher to quickly open 'droid' because that should be the only match. But now they're seeing all the apps which contain 'android' in their package name and they have no idea why. That's not a good UX and for that reason, package name search won't be included. I'm sure you can understand.

**Comment by filikun** [comment]
Is it not possible to let the user change names on the app? I think Niagara launcher uses that functionality to help with just this. The name change acts like a nickname only shown in the launcher and does not actually change the name of the app.

**Comment by tanujnotes** [comment]
It's possible but it's also a lot of work. I'll see what I can do.

**Comment by tanujnotes** [comment]
In my experience, apps with same title are always in the same order in app list. So users will have to remember the order. That's the best solution for now. Thank you.
