### ISSUE TITLE
Double tap to lock disables fingerprint unlocking

### ISSUE THREAD

**Issue by a3y3** [tanujnotes/Olauncher#30]
**Issue**: After double tapping on the home screen to lock, the phone can only be unlocked using PIN/Pattern lock, not fingerprint authentication. Using the fingerprint opens the device PIN/Pattern unlock screen with the message "Device locked by admin".

**Steps to Reproduce**: 
- Enable fingerprint locking in launcher settings
- Lock screen by double tapping
- Try to unlock using fingerprint

**Device**: OnePlus 6
**Android Version**: 10

**Comment by tanujnotes** [comment]
Hi, I'm aware of the issue and I'm working on it. Thank you for your patience.

**Comment by kingfared** [comment]
Hi, I have a MIUI 11 - Redmi Note 9 Pro and fingerprint unlocking works after double tap to lock.

**Comment by tanujnotes** [comment]
What's the Android version? This issue is mostly appearing in Android 10 and above.

**Comment by kaugummiheld** [comment]
I'm using a new Pixel 4a with Android 11 and can confirm that the tap-to-lock screen function leads to me having to input my PW rather than can use the fingerprint to unlock my phone.

**Comment by tanujnotes** [comment]
Latest security rules in Android 10+ don't allow apps to lock some phones normally. I have added a workaround based on what other popular screen lock apps are doing. Please update the app.

**Comment by kaugummiheld** [comment]
Hey, 
I just want to let you know that the fix indeed enables fingerprint unlocking on my Pixel 4a. :+1: 
So thank you very much for that.

But I noticed another rather strange behavior:
Double tap turns the screen of the device off, but then the fingerprint sensor seems to be inactive. Only after I manually press the power button once (the screen remains black) can I use the fingerprint sensor to unlock my device, or click the power button once again to turn the screen on and see my lock screen.

So the double tap seems somehow to turn the screen off, but not fully turn off the device/locking it? (Not sure how to interpret this behavior and I'm not sure if this fixable from your side at all. :shrug:)

**Comment by tanujnotes** [comment]
@kaugummiheld What you're seeing is expected behaviour. Explanation - 

Latest Android security rules do NOT allow apps to lock some phones without disabling the biometric unlock. The workaround is to turn the screen black and set the screen time out to minimum allowed value, which is 5 seconds. When you double tap, screen goes black and the phone will lock itself in 5 seconds, hopefully. During these 5 seconds, you can double tap again to go back to home screen. You can also triple tap anytime to completely lock the phone immediately, disabling the fingerprint/face unlock.
This workaround was inspired by some popular lock screen apps and for now, this is  probably the best that any app can do.

I'll see if I can disable the black screen if fingerprint detected in those 5 seconds. If it  can be added without requiring extra steps or permissions, that should improve the overall experience. Thank you.

**Comment by kaugummiheld** [comment]
@tanujnotes I see. Thank you for the detailed explanation, this helps a lot! 
I was always trying right after the screen went black which of course is no typical use case I guess. 

>  During these 5 seconds, you can double tap again to go back to home screen. You can also triple tap anytime to completely lock the phone immediately, disabling the fingerprint/face unlock.

Can confirm both of these. 

FYI: In the display system settings the shortest time seems to be 15s on my phone. And that seems the period for when the fingerprint sensor is irresponsible (b/c the workaround is working). 
For me that's good enough since I know now what's going on and another double tap can turn it back on. :slightly_smiling_face:

**Comment by Anurag05555y** [comment]
Hi I am Anurag, I feel very advanced using O Launcher But double is not working
