### ISSUE TITLE
Remove Digital Wellbeing Link

### ISSUE THREAD

**Issue by notstarboard** [tanujnotes/Olauncher#435]
I don't understand putting a prominent link explaining how to use Digital Wellbeing into the Olauncher settings. It's not the launcher's role to teach users how to use Android, and Digital Wellbeing isn't even in AOSP. This is meant to be a minimal launcher.

**Comment by tanujnotes** [comment]
I frequently get request to add app blocking features in Olauncher because people don't know about Digital Wellbeing. That's why the link. I believe it's totally in line with the purpose of Olauncher.

But I understand that it can be annoying to some people. I'll add a way to hide  it in the next update.

**Comment by DeadSecTr** [comment]
Just remove the link...let the oLauncher stay minimal AF ;)

**Comment by tanujnotes** [comment]
Long press on 'Digital Wellbeing' text in settings to hide it.
(v4.2.0 and above)
