### ISSUE TITLE
Not able to use lock screen and recent tab feature

### ISSUE THREAD

**Issue by gaurav230187** [tanujnotes/Olauncher#498]
KiIam using realme phone, iam facing a issue where iam not able to use lock screen and recent tab feature , where once i try to use this feature it reverts me to the accessibility setting and in download section it shows me this.
![Screenshot_2024-08-11-01-58-48-55_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/938ffce3-0a14-4e44-84be-774ab74321c9)
![Screenshot_2024-08-11-01-58-48-55_fc704e6b13c4fb26bf5e411f75da84f2]()
![Screenshot_2024-08-11-01-58-43-35_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/ad854c62-1698-4cd9-bdc9-424e53ec1155)

**Comment by DigitalNXZ** [comment]
![Screenshot_20240811-083910_Settings_1](https://github.com/user-attachments/assets/09de2930-32ce-4d17-8a42-3d565e15a6ed)

could u try?: setting - apps - all apps - olauncher (app info) - top right corner? instead of uninstall there should be something like allow restricted whatever- 

if its the same for RealMe ofc.

**Comment by tanujnotes** [comment]
@gaurav230187  https://support.google.com/android/answer/12623953?hl=en
