### ISSUE TITLE
Full Width Apps on Home Screen

### ISSUE THREAD

**Issue by RickAndTired** [tanujnotes/Olauncher#58]
Feature Request - Allow full width apps on the home screen

Apps in the app list are full width, but the home screen doesn't have this

**Comment by tanujnotes** [comment]
This can't be done because it will cause accidental clicks and conflict with gestures like long press to open settings and double tap to lock.

**Comment by RickAndTired** [comment]
Thank you for the reply @tanujnotes and no worries if not, but would it be possible to get an option for half or 75% width? some short name apps are hard to reach.

**Comment by tanujnotes** [comment]
No. It will cause the same problems that I mentioned above. Please understand. 

You can either change the app alignment in settings to right or center or rename the apps to have longer names. Long press on any home screen app, type the app name, add a lot of space, add a dot(.) in the end and tap RENAME. Max length is 20 characters. Don't forget to add the dot or any character in the end otherwise it won't work.

Thank you.

**Comment by RickAndTired** [comment]
No problem, thanks for getting back to me.

I'm still loving Olauncher, thanks for all the great work!

**Comment by Donkey-Doug** [comment]
I don't think it should interfere with gestures. Many apps do this.
