### ISSUE TITLE
[Feature Request] Option to show more Apps on the launcher

### ISSUE THREAD

**Issue by Tomptez** [tanujnotes/Olauncher#73]
Currently, the maximum number of apps on the homescreen is 8. 

While I agree that this is visually quite pleasing and minimalistic I think for devices with a really large screen it would be great if there was an option to have more (maybe 10 or 12) apps shown in the launcher. I want to use my phone as a tool and I have more than 8 apps that I use daily so for me personally 10 would be an ideal number in terms of efficiency.

**Comment by tanujnotes** [comment]
Can't add more than 8 apps for few reasons.
1. They cause issue on smaller screens.
2. Can't make them scrollable either because it will interfere with swipe up/down gestures and others that I might add later.
3. If I came up with an elegant solution to this problem, I'm planning to add some sort of pro version and this feature will be available only to pro users.

I hope you can understand. Thank you.

**Comment by Tomptez** [comment]
That would be really unfortunate. First of all I think users with smaller screen would just not use 10 apps if it doesn't work on their device (and you could argue the same for 8 launchers) but you could probably restrict its use to users of a minimum screen size quite easily as well.

Since I now fixed this for my personal use I made a [pull request](https://github.com/tanujnotes/Olauncher/pull/74#issue-571143326) and I really hope you give it another consideration

**Comment by tanujnotes** [comment]
You "think"... but I know. I've already had multiple complaints that with 8 apps on screen, it overlaps with the clock widget or just goes really close to it and doesn't look good. I fixed it by setting smaller text size for lower resolution screens. It's kind of working for now. 

Besides, more than 8 apps will be available in the pro version with clear warnings about smaller screens. Before that happens, I'll have to add text size change settings so that people can squeeze more apps on home screen if they want.
