### ISSUE TITLE
[REQUEST] - ????

### ISSUE THREAD

**Issue by Z7AL3G37VZ7** [tanujnotes/Olauncher#8]
Tanuj,

Your launcher is amazing, it similar to the launcher I'm currently using a decluttered launcher. If possible could you add a few simple things that would definitely make this launcher stand out.

If you tried a decluttered launcher
You will notice the similarity and how convenient it is to swipe down for the browser of your choice. Swiping left & right to launch the app of your choice. As well tapping the calendar & clock to launch the app of your choice.

Add list
- Option to Disable swipe down notifications center ( in place of Swipe down to search the internet (launch users default internet browser, we all use different browsers
- Swipe left & right to open custom apps and the option to disable swiping left & right
- Launch custom apps with calendar & clock
- Rename apps on the home screen
- If possible,  Hide specific apps in the app Drawer ( some apps run in the background and do not need to be in the App Drawer)

I notice others have requested 1 or 2 feature from my list. They were rejected do to a lack of request. Unfortunately not many people know of this amazing launcher or like minimalist launchers. If its funding you need to get these feature add to the launcher that's not a problem.

**Comment by tanujnotes** [comment]
Thank you for your detailed comment. Yes I have used decluttered launcher. It's fantastic and it also served as an inspiration for Olauncher. Let me go through your points one by one.

- Swipe down for notification center is a standard behavior in many Android phones and frequently used so I don't want to mess with that. Having said that, an easier way to search is equally important. I'm thinking about adding a search icon at the bottom left corner but I'm open to suggestion regarding search design.
- Customizing left right swipes will be available in the next update.
- Default clock and calendar apps are launched on clicking the time and date respectively. I don't see any strong reason to change that unless more than a few people want it.
- Nice to have but doesn't really serve a purpose. Once again, can be added but only if a lot of people require it.
- This has been requested before by some of my friends. It will eventually be added. Maybe in the next update. Maybe in the one after that. Depends on the complexity of implementation.

Olauncher is minimal because I prefer it that way. But since more and more feature requests are coming in, I'm planning to create another one called Olauncher+. It will be based on this one but will have all kinds of customization people need. And of course, it will be free and open source, forever.

About the funding, I don't require it per se, but if anyone wants to support, [they can buy me a coffee](https://www.buymeacoffee.com/tanujnotes). :)

**Comment by Z7AL3G37VZ7** [comment]
Thanks Tanuj for the quick response.

Look like I'm stuck with this boring black and white screen a little longer. I got a little excited to see someone have the same interest in a decluttered launcher an remake it with all its functions. While adding the ability to use live/wallpapers and more apps on the home screen.

Also I think there's a miss understanding. I don't mean to disable the notifications center, but to have the choice to swipe down to either launch a specific app (internet browser) or notifications center. You still are able to swipe down from the top to bring down the NC.

Its not a priority but your right NICE to have. The purpose for renaming an app on the home screen, its an eyesore to see long pointless names such as YouTube Vanced, bright memory mobile, Samsung music, etc.

The calendar & time 
Many users don't use the default calendar there are better apps. Same with the time a user may clicking on the time to bring up the weather or meditation timer. A choice would be awesome.

BTW - the long hold is too sensitive
Just an idea - add a small icon to the bottom right that only appears when tapping once on the screen.

Thanks for your time & amazing work will definitely come back in the future to see the progress.

Later!!

**Comment by tanujnotes** [comment]
Thank you for the feedback. I'll try my best to make Olauncher better. I hope you make it your default launcher next time you try it.
