### ISSUE TITLE
[Feature] Uninstall option next to "Hide"

### ISSUE THREAD

**Issue by jacksongoode** [tanujnotes/Olauncher#98]
When long pressing on an app in the app drawer it would be a great shortcut to have an uninstall option either as a "Remove" or "Uninstall" text or possible an "x" icon next to the information icon to conserve space.

**Comment by 86Atlas** [comment]
Please yes, that would solve so many taps.

**Comment by Donkey-Doug** [comment]
As well as a rename option.

**Comment by jlemonde** [comment]
I need that too!! Since I started using this launcher I noticed how much useless crap I have got installed on my device, so I would currently switch to another launcher to uninstall stuff....

**Comment by tanujnotes** [comment]
You can long press on an app, tap on ( i ) icon. It will open app info page which generally has option to uninstall. Or you can uninstall from Play Store. Either way, you don't need to switch to other launcher.

**Comment by jacksongoode** [comment]
> You can long press on an app, tap on ( i ) icon. It will open app info page which generally has option to uninstall. Or you can uninstall from Play Store. Either way, you don't need to switch to other launcher.

I think the thought that some of us have is that for a simple operation like uninstalling, it would be nice to uninstall an app without leaving the homescreen, using a simple uninstall status popup, instead of navigating into settings and uninstalling within a new app.

**Comment by jlemonde** [comment]
@tanujnotes I uninstalled a few apps this way, but it is very unpractical because the launcher does not remember where on the app list you were before opening an info page, so you have to scroll back down to continue uninstalling apps. This makes it very annoying, for this reason I currently have no other convenient option than to switch to another launcher. This is why I believe there should be an option to directly uninstall stuff without quitting the launcher, as @jacksongoode also suggested. 

I believe that this is super important because new-comers to Olauncher would probably like I did notice how many useless app they were storing on their device right after seeing that app list for the first time, so if uninstalling apps is not convenient it will be a big drawback.

**Comment by tanujnotes** [comment]
That's a good point regarding new-comers. This is still not a high priority though. I'll see what I can do.

**Comment by JacksonCampbell99** [comment]
I like the idea of a simple <kbd>X</kbd> next to the <kbd>ⓘ</kbd>.

**Comment by arcstur** [comment]
Currently, I think this shouldn't be implemented. You probably don't uninstall apps every single day. As this is a minimalist launcher, it is expected that certain things are not implemented to preserve the minimalism. 

The hide button is launcher-specific, that's why it's there. Uninstalling is system-specific, so click the (i) to go to the system app settings page. 

I do however think that a rename functionality would be great. Since the app heavily uses the apps' names to open them, it would be good to be able to modify them.
